Change deploy-specs.scurl to V0.6.1 and improve the make-zips script to fail if certain .scurl files are not built.
git-svn-id: https://curl-ext.svn.sourceforge.net/svnroot/curl-ext@68 8a9b41f1-96dd-4b0b-9fd8-a45abf92b436

diff --git a/LIBRARY/trunk/tools/make-zips b/LIBRARY/trunk/tools/make-zips
--- a/LIBRARY/trunk/tools/make-zips
+++ b/LIBRARY/trunk/tools/make-zips
@@ -12,6 +12,16 @@ DISTDIR="$SRCROOT/$DIST"
 echo "Packing $DDIR from $SRCROOT into $DIST"
 DISTSRC="$DISTDIR/$DDIR-src"
 DISTDOC="$DISTDIR/$DDIR-doc"
+
+PCURLDIR=$SRCROOT/deploy/$DDIR/
+BGTDIR=$SRCROOT/deploy/$DDIR/BackgroundTask
+if ! test -f "$BGTDIR/BackgroundTaskRemoteInterface.scurl" ; then
+    echo "?? $BGTDIR/BackgroundTaskRemoteInterface.scurl missing - check the project file."
+fi
+if ! test -f "$BGTDIR/BackgroundTaskRemoteInterfacePackage.scurl" ; then
+    echo "?? $BGTDIR/BackgroundTaskRemoteInterfacePackage.scurl missing - check the project file."
+fi
+
 FLAGS="-av"
 if test -d "$DISTDIR" ; then
     echo "-- $DISTDIR already exists: Updating only"
